ALL_LOGIN_URL = {
    '内蒙古': 'https://etax.neimenggu.chinatax.gov.cn/login-web/index.html?v=20190701105613#/',
    '甘肃': 'https://etax.gansu.chinatax.gov.cn/bszm-web/apps/views/beforeLogin/indexBefore/pageIndex.html',
    '陕西': 'https://etax.shaanxi.chinatax.gov.cn/xxmh/html/index.html',
    '青岛': 'https://etax.qingdao.chinatax.gov.cn:7553/sso/login?service=https%3A%2F%2Fetax.qingdao.chinatax.gov.cn%2Fportal%2F',
    '江苏': 'https://etax.jiangsu.chinatax.gov.cn/sso/login',
    '浙江': 'https://etax.zhejiang.chinatax.gov.cn/zjgfdzswj/main/index.html',
    '河南': 'https://dzswj.ha-n-tax.gov.cn/web/dzswj/ythclient/mh.htm',
    '河北': 'https://etax.hebei.chinatax.gov.cn/bszm-web/apps/views-zj/index/index.html',
    '广东': 'https://www.etax-gd.gov.cn/xxmh/html/index.html',
    '上海': 'https://etax.shanghai.chinatax.gov.cn/wszx-web/bszm/apps/views/beforeLogin/indexBefore/pageIndex.html#/',
    '北京': 'https://etax.beijing.chinatax.gov.cn/xxmh/html/index.html',
    '辽宁': 'https://etax.liaoning.chinatax.gov.cn/sword?ctrl=LoginCtrlTmp_logout',
    '安徽': 'https://etax.anhui.chinatax.gov.cn/',
    '江西': 'https://etax.jiangxi.chinatax.gov.cn/etax/jsp/index.jsp',
    '重庆': 'https://etax.chongqing.chinatax.gov.cn/',
    '湖南': 'https://etax.hunan.chinatax.gov.cn/wsbs/toLogin.do',
    '四川': 'https://etax.sichuan.chinatax.gov.cn/home/',
    '宁波': 'https://etax.ningbo.chinatax.gov.cn/nbdzswj-web/apps/views/beforeLogin/indexBefore/pageIndex.html#/?_t=1563945395113',
    '山西': 'https://etax.shanxi.chinatax.gov.cn/login',
    '山东': 'http://218.57.142.38:8080/',
    '福建': '',
    '天津': 'https://wsswj.tjsat.gov.cn/apps/view/login.html',
    '吉林': 'https://etax.jilin.chinatax.gov.cn:10812/sword?ctrl=LoginCtrlTmp_logout',
    '黑龙江': 'https://www.hljetax.gov.cn/',
    '湖北': 'https://wsswj.hb-n-tax.gov.cn/portal/',
    '广西': 'https://etax.guangxi.chinatax.gov.cn:9723/web/dzswj/ythclient/mh.html',
    '海南': 'https://etax.hainan.chinatax.gov.cn/sword?ctrl=LoginCtrlTmp_logout',
    '贵州': 'https://etax.guizhou.chinatax.gov.cn/xxmh/html/index.html',
    '云南': 'https://etax.yunnan.chinatax.gov.cn/zjgfdzswj/main/index.html',
    '西藏': 'https://etax.xizang.chinatax.gov.cn:8443/sword?ctrl=DZBSXTKJ027HomePagelCtrl_welcome',
    '青海': 'https://etax.qinghai.chinatax.gov.cn/xxmh/html/index.html',
    '宁夏': 'https://etax.ningxia.chinatax.gov.cn/sword?ctrl=LoginCtrlTmp_logout',
    '新疆': 'https://etax.xinjiang.chinatax.gov.cn/wszx-web/bszm/apps/views/beforeLogin/indexBefore/pageIndex.html',

}
ALL_TAX_NAME = [
    '内蒙古',
    '甘肃',
    '陕西',
    '青岛',
    '江苏',
    '浙江',
    '河南',
    '河北',
    '广东',
    '上海',
    '北京',
    '辽宁',
    '安徽',
    '江西',
    '重庆',
    '湖南',
    '四川',
    '宁波',
    '山西',
    '山东',
    '福建',
    '天津',
    '吉林',
    '黑龙江',
    '湖北',
    '广西',
    '海南',
    '贵州',
    '云南',
    '西藏',
    '青海',
    '宁夏',
    '新疆',
]

ALL_TAX_AREA_CODE = {
    '内蒙古': '15',
    '甘肃': '62',
    '陕西': '61',
    '青岛': '1',
    '江苏': '32',
    '浙江': '33',
    '河南': '41',
    '河北': '13',
    '广东': '44',
    '广西': '45',
    '上海': '31',
    '北京': '11',
    '辽宁': '21',
    '安徽': '34',
    '江西': '36',
    '重庆': '2',
    '湖南': '43',
    '四川': '51',
    '宁波': '66',
    '山西': '14',
    '山东': '37',
    '福建': '35',
    '天津': '12',
    '吉林': '22',
    '黑龙江': '23',
    '湖北': '42',
    '海南': '46',
    '贵州': '52',
    '云南': '53',
    '西藏': '54',
    '青海': '63',
    '宁夏': '64',
    '新疆': '65',
}

# 数据库配置
DB_CONFIG = {
    'host': '127.0.0.1',
    'port': 3306,
    'user': 'root',
    'passwd': 'madl1994',
    'db': 'supervisory_taxweb',
    'charset': 'utf8'
}
